# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: planningpoker
description: Planning Poker Online app for Android and iOS.

publish_to: "none"

version: 3.1.01+31

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  cloud_firestore: 3.1.5
  cupertino_icons: 1.0.4
  firebase_auth: 3.3.4
  firebase_core: 1.10.6
  flutter_launcher_icons: 0.9.2
  flutter_markdown: 0.6.9
  flutter_redux: 0.8.2
  intro_slider: 3.0.2
  json_annotation: 4.4.0
  launch_review: 3.0.1
  logger: 1.1.0
  package_info: 2.0.2
  redux: 5.0.0
  share: 2.0.4
  shared_preferences: 2.0.11
  url_launcher: 6.0.17
  vibration: 1.7.4-nullsafety.0
  fast_immutable_collections: 7.1.2
  progress_indicators: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.7
  json_serializable: 6.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android_app_logo.png"
  image_path_ios: "assets/icon/ios_app_logo.png"
