# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: planningpoker
description: Planning Poker Online app for Android and iOS.

publish_to: "none"

version: 3.1.01+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  cloud_firestore: 1.0.6
  cupertino_icons: 1.0.2
  firebase_auth: 1.1.1
  firebase_core: 1.0.4
  flutter_launcher_icons: 0.9.0
  flutter_markdown: 0.6.1
  flutter_redux: 0.8.2
  intro_slider: 2.4.0
  json_annotation: 4.0.1
  launch_review: 3.0.1
  logger: 1.0.0
  package_info: 2.0.0
  redux: 5.0.0
  share: 2.0.1
  shared_preferences: 2.0.5
  url_launcher: 6.0.3
  vibration: 1.7.4-nullsafety.0
  fast_immutable_collections: 4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.12.2
  json_serializable: 4.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android_app_logo.png"
  image_path_ios: "assets/icon/ios_app_logo.png"
