# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: planningpoker
description: Planning Poker Online app for Android and iOS.

publish_to: "none"

version: 3.0.0+24

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  flip_card: ^0.4.4
  flutter_launcher_icons: ^0.8.1
  flutter_markdown: ^0.5.1
  flutter_redux: ^0.7.0
  intro_slider: ^2.3.3
  json_annotation: ^3.1.1
  launch_review: ^2.0.0
  logger: ^0.9.4
  package_info: ^0.4.3+2
  redux: ^4.0.0+3
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android_app_logo.png"
  image_path_ios: "assets/icon/ios_app_logo.png"
