# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: planningpoker
description: Planning Poker Online app for Android and iOS.

publish_to: "none"

version: 3.0.1+26

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flip_card: ^0.4.4
  flutter_launcher_icons: ^0.9.0
  flutter_markdown: ^0.6.0
  flutter_redux: ^0.7.0
  intro_slider: ^2.3.4
  json_annotation: ^4.0.0
  launch_review: ^3.0.1
  logger: ^0.9.4
  package_info: ^2.0.0
  redux: ^4.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.2
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android_app_logo.png"
  image_path_ios: "assets/icon/ios_app_logo.png"
