# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Run unit tests"
  lane :test do
    Dir.chdir ".." do
      sh("flutter", "test")
    end
  end

  desc "Build a new appbundle"
  lane :appbundle do
    Dir.chdir ".." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--obfuscate", "--split-debug-info=build/app/outputs/symbols")
    end
  end

  desc "Deploy a new beta version to the Google Play"
  lane :beta do
    Dir.chdir ".." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--obfuscate", "--split-debug-info=build/app/outputs/symbols")
    end
    upload_to_play_store(track: "beta",release_status:"draft", aab:"../build/app/outputs/bundle/release/app-release.aab")
  end
end
